### ISSUE TITLE
ESP32 project uses CMake as the build system. So you can add your custom source file under `afr_module_sources()` section within the shadow demo [CMakeFile](https://github.com/aws/amazon-freertos/blob/master/demos/coreMQTT/CMakeLists.txt#L9). Header file can be placed in a directory and the directory path can be added to the above CMakeFile as follows:

### ISSUE THREAD

**Issue by SGOSAI602** [aws/amazon-freertos#2698] opened 2020-11-04 12:48 UTC
ESP32 project uses CMake as the build system. So you can add your custom source file under `afr_module_sources()` section within the shadow demo [CMakeFile](https://github.com/aws/amazon-freertos/blob/master/demos/coreMQTT/CMakeLists.txt#L9). Header file can be placed in a directory and the directory path can be added to the above CMakeFile as follows:

```
afr_module_include_dirs(
    ${AFR_CURRENT_MODULE}
    INTERFACE
        "<header file directory path>"
)
```

_Originally posted by @ravibhagavandas in https://github.com/aws/amazon-freertos/issues/2661#issuecomment-721326599_

**Comment by ravibhagavandas** [comment] 2020-11-04 18:18
@SGOSAI602 
I am closing this issue as it seems a duplicate of #2661. Please post any further questions you have in the original issue.

**Closed by ravibhagavandas** 2020-11-04 18:18 UTC
