### ISSUE TITLE
common-io: Timer callback test case pends forever on semaphore

### ISSUE THREAD

**Issue by osloapps-max** [aws/amazon-freertos#2567] opened 2020-10-14 13:10 UTC
**Describe the bug**
The **AFWP_IotTimer_Callback** test case will use portMAX_DELAY as timeout when pending for the semaphore. This means the test case will be left hanging in case there is an timer error.

**System information**
- Which hardware board or part numbers?
Texas Instruments CC3220SF
- IDE used
- Operating System [Windows|Linux|MacOS]
- Version of FreeRTOS (run ``git describe --tags`` to find it)
Windows
- Project [Custom Application|MQTT|Shadow|Greengrass|OTA|Device Defender|TCP Echo|Sub pub Demo|Simple TCP Server]
aws_tests
- If your project is a Custom Application, please add the relevant code snippet in the section `Code to reproduce the bug`. 

**Expected behavior**
The test should use a timeout proportional to that of the expected delay to allow for the test to fail in case the callback is not received within a given interval.

I personally believe the timeout should be >4 times larger then the expected timeout . This to take headroom for differences in timer resolution based on device implementations. I think this should be the case for all Timer test cases.

Thank you!

**Comment by lundinc2** [comment] 2020-11-12 02:35
I am closing this issue as I believe the problem is solved. Please re-open this if you have any concerns.

Thanks,

Carl

**Closed by lundinc2** 2020-11-12 02:35 UTC
