### ISSUE TITLE
Memory leak when publishing with mqtt to the cloud

### ISSUE THREAD

**Issue by MrMelon1232** [aws/amazon-freertos#2888] opened 2020-12-15 17:15 UTC
Whenever my apps and program publishes to a specific topic to the cloud, a memory leak occurs. I can't really see where a memory leak can occur in my code and was wondering if there might be something about the mqtt publish function that takes care of memory that I am not aware of. Any help would be appreciated.

**System information**
- Board: ESP32
- OS: Linux
- Using own personal app

Code used
```
void test_loops()
{
    extern QueueHandle_t xQueue_sensor_payload; 
    extern QueueHandle_t xQueue_bme280_payload;
    while(WIFI_IsConnected(&mqttApp.pxNetworkParams))
    {
        heap_size = xPortGetFreeHeapSize();    
        IotLogInfo("Heap size left before publishing : %u", heap_size);
        //Shadow sensor update
        if(publish_shadow_update(&mqttApp.xMqttContext, mqttApp.usPublishPacketIdentifier) == pdPASS)
        {
            IotLogInfo("Shadow payload publish success");
        }
    
        //Sensor data payload
        if(publish_sensor_data(&mqttApp.xMqttContext, mqttApp.usPublishPacketIdentifier) == pdPASS)
        {
            CHECK_ERROR_CODE(esp_task_wdt_reset(), ESP_OK);
            IotLogInfo("Sensor payload publish success!");
            heap_size = xPortGetFreeHeapSize();    
            IotLogInfo("Heap size left after publishing sensor data : %u", heap_size);
        }

        //BME280 payload
        if(publish_bme280_data(&mqttApp.xMqttContext, mqttApp.usPublishPacketIdentifier) == pdPASS)
        {
            CHECK_ERROR_CODE(esp_task_wdt_reset(), ESP_OK);
            IotLogInfo("BME280 payload success!");
            heap_size = xPortGetFreeHeapSize();    
            IotLogInfo("Heap size left after publishing bme280 : %u", heap_size);
        }
        heap_size = xPortGetFreeHeapSize();    
        IotLogInfo("Heap size left after publishing payloads : %u", heap_size);
        vTaskDelay(2000);
    }
}

```

Here is one of the publish_sensor_data function which is the same as publish_bme280_data but with different payloads
```
bool publish_sensor_data(MQTTContext_t * xMqttContext, uint16_t usPublishPacketIdentifier)
{
    bool status;
    char sensor_data_Document[SENSOR_PAYLOAD_SIZE];
    extern QueueHandle_t xQueue_sensor_payload; 
    if(xQueueReceive(xQueue_sensor_payload, &sensor_data_Document, 0) == pdPASS)
    {
        heap_size = xPortGetFreeHeapSize();    
        IotLogInfo("Heap size left before mallocs : %u", heap_size);
        //Getting thingname from nvs
        char *thingname = fsonet_getThingName();
        size_t thingnamelength = snprintf(NULL, 0, "%s", thingname) + 1;
        size_t topicnamelength = 19 + thingnamelength;
        char *topicname = malloc(topicnamelength);
        snprintf(topicname, topicnamelength, "%s%s", "topicname", "topicspecifier");

        //Getting payload data
        size_t nbytes = snprintf(NULL, 0, "%s", sensor_data_Document) + 1;
        char *payload = malloc(nbytes);
        IotLogDebug("NBYTES: %d\n", nbytes);
        snprintf(payload, nbytes, "%s", sensor_data_Document);

        heap_size = xPortGetFreeHeapSize();    
        IotLogInfo("Heap size left before sensor data publish functions : %u", heap_size);

        status = mqttPublish(xMqttContext, usPublishPacketIdentifier, topicname, payload, nbytes - 1);
        if(status == pdPASS)
            IotLogInfo("Published successfully to topic: %s", topicname);
        heap_size = xPortGetFreeHeapSize();    
        IotLogInfo("Heap size left after publish function sensor data : %u", heap_size);    
        free(thingname);
        free(topicname);
        free(payload);    
        heap_size = xPortGetFreeHeapSize();    
        IotLogInfo("Heap size left after freeing mallocs : %u", heap_size);
    }
    else
        status = pdFAIL;
    
    return status;
}
```
Here is the mqttPublish function
```
bool mqttPublish(MQTTContext_t * xMqttContext, uint16_t usPublishPacketIdentifier, char * topicname, const void * payload, size_t payloadLength )
{
    MQTTStatus_t xResult;
    bool status = pdPASS;
    //Publish information
    MQTTPublishInfo_t xMQTTPublishInfo;
    ( void ) memset( ( void * ) &xMQTTPublishInfo, 0x00, sizeof( xMQTTPublishInfo ) );

    xMQTTPublishInfo.qos = MQTTQoS0;
    xMQTTPublishInfo.retain = false;
    xMQTTPublishInfo.pTopicName = topicname;
    xMQTTPublishInfo.topicNameLength = ( uint16_t ) strlen( topicname );
    xMQTTPublishInfo.pPayload = payload;
    xMQTTPublishInfo.payloadLength = payloadLength;
    

    //Get packet ID and publish
    usPublishPacketIdentifier = MQTT_GetPacketId( xMqttContext );
    IotLogDebug("This is the packet ID for publish update: %d", usPublishPacketIdentifier);
    xResult = MQTT_Publish(xMqttContext, &xMQTTPublishInfo, usPublishPacketIdentifier);
    if( xResult != MQTTSuccess )
    {
        status = pdFAIL;
        IotLogDebug("Failed to send PUBLISH message to broker");
    }
    return status;
}

```

Ouput from terminal
```
771 12088 [Wifi connectivi] [INFO ][MQTT_APP][120880] Heap size left before publishing : 95972
772 12089 [Wifi connectivi] [INFO ][MQTT_APP][120890] Heap size left before mallocs : 95996
773 12090 [Wifi connectivi] [INFO ][MQTT_APP][120900] Heap size left before sensor data publish functions : 95660
774 12092 [Wifi connectivi] [INFO ][MQTT_APP][120920] Published successfully to topic: fsonet/sensor-data/fsonet-12
775 12093 [Wifi connectivi] [INFO ][MQTT_APP][120930] Heap size left after publish function sensor data : 92384
776 12093 [Wifi connectivi] [INFO ][MQTT_APP][120930] Heap size left after freeing mallocs : 92820
777 12095 [Wifi connectivi] [INFO ][MQTT_APP][120950] Sensor payload publish success!
778 12096 [Wifi connectivi] [INFO ][MQTT_APP][120960] Heap size left after publishing sensor data : 93916
779 12099 [Wifi connectivi] [INFO ][MQTT_APP][120990] Published successfully to topic: fsonet/bme280-data/fsonet-12
780 12100 [Wifi connectivi] [INFO ][MQTT_APP][121000] BME280 payload success!
781 12101 [Wifi connectivi] [INFO ][MQTT_APP][121010] Heap size left after publishing bme280 : 94300
782 12102 [Wifi connectivi] [INFO ][MQTT_APP][121020] Heap size left after publishing payloads : 94404
```

Thank you!

**Comment by lundinc2** [comment] 2020-12-15 20:22
Hi @MrMelon1232,

Thank you for this report, what version of the codebase is this occurring for you? I will investigate this issue.

Thanks,

Carl

**Comment by MrMelon1232** [comment] 2020-12-16 15:05
HI @lundinc2,

This occured with this commit: f60e9e4fd88b0b280de1e1a22f4661409d0294c6. The memory leaks seem to be inconsistent as in different amounts of bytes/words are being leaked and its not always the same amount.

**Comment by muneebahmed10** [comment] 2020-12-16 22:02
Hi @MrMelon1232 ,

The coreMQTT library only allocates static memory, so any memory leaks you observe are likely elsewhere. Does the heap size continue to decrease with additional iterations of the loop? Can you also print the result of `xPortGetMinimumEverFreeHeapSize()` to see if the lowest free heap is decreasing?

**Comment by MrMelon1232** [comment] 2020-12-17 17:14
Hi @muneebahmed10,
Yes this occurs at every iteration of the loop. Task memory stack seems to be unchanged but the lowest free heap is decreasing as well but randomly. Examples of such is it would remain unchanged for 5 minutes but then decrease the next 5 minutes.

**Comment by muneebahmed10** [comment] 2020-12-17 20:08
Hi @MrMelon1232 ,

Is only an issue when using MQTT? If you comment out your calls to `MQTT_Publish()`, do you still see leak?

**Comment by MrMelon1232** [comment] 2020-12-22 21:09
Hi @muneebahmed10,
 
After doing a few tests I can confirm that the memory leak occurs even without the ```MQTT_Publish()``` function. But I am still unsure where the memory leak could occur even with the task stack memory being unchanged.

**Comment by muneebahmed10** [comment] 2020-12-23 06:03
Hi @MrMelon1232,

As a starting point, I'd recommend running one of the [AWS demos](https://github.com/aws/amazon-freertos/tree/master/demos) on your board, while monitoring your heap usage. If there's no leak there, then you will know the issue is from your personal application. Beyond that, I can suggest either substituting your app in piece by piece, or reviewing any parts of your application dealing with memory allocation.

> the lowest free heap is decreasing as well but randomly. Examples of such is it would remain unchanged for 5 minutes but then decrease the next 5 minutes.

Is it possible there's some task you have that's running irregularly?

**Comment by muneebahmed10** [comment] 2021-01-11 21:28
Hi @MrMelon1232,

Were you able to find your memory leak? We will close this issue if we don't hear back from you.

Thanks

**Closed** 2021-01-26 00:04 UTC
