### ISSUE TITLE
_httpReconnect always fails

### ISSUE THREAD

**Issue by Sherryzhang2** [aws/amazon-freertos#3075] opened 2021-03-30 03:41 UTC
**Describe the bug**
In the OTA process, I choice the HTTPS to download the image data. But it always fails in _httpReconnect.
Th reason is that in IotHttpsClient_Connect, it disconnects the connection by calling IotHttpsClient_Disconnect. IotHttpsClient_Disconnect  firstly calls  _networkDisconnect to disconnect the connection in which the _FLAG_RECEIVE_TASK_EXITED flag is cleared and the _FLAG_SHUTDOWN flag is set. Then IotHttpsClient_Disconnect  calls _networkDestroy to destroy the connect in which it asserts that connection flag _FLAG_RECEIVE_TASK_EXITED bit is set.

Proposed fix, in IotNetworkAfr_Destroy, the connection flag _FLAG_SHUTDOWN should be used in the assert instead of the _FLAG_RECEIVE_TASK_EXITED flag which has already be cleared in  IotNetworkAfr_Close.

**Comment by Sherryzhang2** [comment] 2021-03-30 03:42
I think the root cause of https://github.com/aws/amazon-freertos/issues/3073 is the same as this issue.

**Comment by muneebahmed10** [comment] 2021-03-31 19:48
Hi @Sherryzhang2,

Thank you for bringing this to our attention. I've created #3082 to fix this. Can you pull that change and confirm that the issue is resolved?

Thank you

**Comment by muneebahmed10** [comment] 2021-04-15 02:06
Hi @Sherryzhang2,

Thank you again for reporting this bug. I will close this issue. Please open another issue if you have any other questions or bug reports.

Thank you

**Closed by muneebahmed10** 2021-04-15 02:06 UTC

**Comment by Sherryzhang2** [comment] 2021-04-15 02:29
@muneebahmed10 Thanks for your prompt fix.
